name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Runs the workflow when changes are pushed to the main branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4  # Updated version

      - name: Upload files
        uses: actions/upload-pages-artifact@v1  # Use v1 (since v4 does not exist)
        with:
          path: .  # Upload all files in the repo

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4  # Correct latest version
